# Generated by Django 4.2.1 on 2023-05-22 13:30

from django.db import migrations, models
import groceries.storage_backend


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='immage_url',
            field=models.FileField(default=None, storage=groceries.storage_backend.PublicMediaStorage(), upload_to=''),
        ),
    ]
