# Generated by Django 4.2.1 on 2023-05-23 16:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_post_immage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='greengrocer',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
        ),
    ]
